src/Entity/Contact.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ContactRepository")
 */
class Contact
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(
     *    message = "{{ value }}' is not correct.",
     *    checkMX = true
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    public function getId()
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }
}

src/Form/ContactType.php
<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')
            ->add('email')
            ->add('image')
            ->add('date')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ContactController extends Controller
{
    /**
     * @Route("/contact", name="contact")
     */
    public function index() {

        $contact = $this->getDoctrine()
            ->getRepository(Contact::class)
            ->findAll();

        return $this->render('contact/index.html.twig', [
            'controller_name' => 'ContactController',
            'contact' => $contact
        ]);
    }

    /**
     * @Route("/contact/new", name="new_contact")
     */
    public function add(Request $request) {

        $contact = new Contact();
        $contact->setDate(new \DateTime());

        $form = $this->createForm(ContactType::class, $contact)
            ->add('save', SubmitType::class, array('label' => 'Create contact'));

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($contact);
            $em->flush();

            return $this->redirect('/contact');
        }

        return $this->render('contact/new.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/contact/delete/{id}", name="delete_contact")
     */
    public function delete($id) {

        $contact = $this->getDoctrine()
            ->getManager();
        $cont = $contact
            ->getRepository(Contact::class)
            ->find($id);

        $contact->remove($cont);
        $contact->flush();

        return $this->redirect('/contact');
    }

    /**
     * @Route("/contact/{id}/edit", name="edit_contact")
     */
    public function edit(Request $request, Contact $contact): Response {

        $form = $this->createForm(ContactType::class, $contact)
        ->add('save', SubmitType::class, array('label' => 'Save the modification'));

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirect('/contact');
        }

        return $this->render('contact/edit.html.twig', [
            'contact' => $contact,
            'form' => $form->createView(),
        ]);
    }
}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href=" {{ asset('index.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Serif" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
{% endblock %}

{% block body %}

    <div class="container">
        <h1> Edit a contact </h1>
        <div class="preview">
            {{ form_start(form) }}
                {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
    </div>

    <h2><a class="backtolist" href="/contact">Back to the contact list</a></h2>
    <td class="btn"><a class="delete" href="{{ path('delete_contact', {'id': contact.id}) }}">Delete</a></td>
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href=" {{ asset('index.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Serif" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Umail</h1>
        <h2><a class="newcontact" href="/contact/new">New contact</a></h2>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Last name</th>
                    <th>Email</th>
                </tr>
                {% for contact in contact %}
                    <tr>
                        <td>{{ contact.firstName }}</td>
                        <td>{{ contact.lastName }}</td>
                        <td>{{ contact.email }}</td>
                        <td class="btn"><a class="delete" href="{{ path('delete_contact', {'id': contact.id}) }}">Delete</a></td>
                        <td class="btn"><a class="edit" href="{{ path('edit_contact', {'id': contact.id}) }}">Edit</a></td>
                    </tr>
                {% endfor %}
            </table>
        <h2><a class="backtolist" href="/">Back to list</a></h2>
    </div>
{% endblock %}

templates/contact/new.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link href=" {{ asset('index.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Serif" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
{% endblock %}

{% block title %}
    New contact
{% endblock %}

{% block body %}
    <div class="container">
        <h1> Register a new contact </h1>
        <div class="preview">
            {{ form_start(form) }}
                {{ form_widget(form) }}
            {{ form_end(form) }}
        </div>
        <h2><a class="backtolist" href="/">Back to list</a></h2>
    </div>
{% endblock %}